###
POST http://localhost:5000/user/login
content-type: application/json

{
    "email": "ktkim@elicer.com",
    "password": "1234"
}

###
POST http://localhost:5000/award/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 
content-type: application/json

{
    "user_id": "96cdd36d-0b33-4969-a69a-8eb4e804dff2",
    "title": "상장",
    "description": "좋은 상장이에요"
}

###
GET http://localhost:5000/awards/81a9e8e1-bc4e-484d-99f4-406bafc9c400
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 


###
PUT http://localhost:5000/awards/81a9e8e1-bc4e-484d-99f4-406bafc9c400
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 
content-type: application/json


{
    "user_id": "96cdd36d-0b33-4969-a69a-8eb4e804dff2",
    "title": "상장2",
    "description": "좋은 상장이에요2"
}

###
DELETE http://localhost:5000/awards/81a9e8e1-bc4e-484d-99f4-406bafc9c400
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 

###
GET http://localhost:5000/awardlist/96cdd36d-0b33-4969-a69a-8eb4e804dff2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 


