###
POST http://localhost:5000/user/login
content-type: application/json

{
    "email": "ktkim@elicer.com",
    "password": "1234"
}

###
POST http://localhost:5000/certificate/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 
content-type: application/json

{
    "user_id": "96cdd36d-0b33-4969-a69a-8eb4e804dff2",
    "title": "자격증",
    "description": "좋네요",
    "when_date": "오늘인가"
}

###
GET http://localhost:5000/certificates/256879a7-52fa-42be-ac38-204559bb56a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 


###
PUT http://localhost:5000/certificates/256879a7-52fa-42be-ac38-204559bb56a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 
content-type: application/json

{
    "user_id": "96cdd36d-0b33-4969-a69a-8eb4e804dff2",
    "title": "자격증2",
    "description": "좋네요2",
    "when_date": "오늘인가2"
}

###
DELETE http://localhost:5000/certificates/256879a7-52fa-42be-ac38-204559bb56a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 

###
GET http://localhost:5000/certificatelist/96cdd36d-0b33-4969-a69a-8eb4e804dff2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTZjZGQzNmQtMGIzMy00OTY5LWE2OWEtOGViNGU4MDRkZmYyIiwiaWF0IjoxNjQ0NTg1NDIxfQ.GmViFFz5UqhBFNvI9mquWdw1ynvtqD-Oz3oB7CfCPbI 


